version: 2
updates:
  - package-ecosystem: helm
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: update-helm-deps
      include: scope
    open-pull-requests-limit: 2
    target-branch: main
