{{- if .Values.upstreamProxy.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-upstream
  labels:
    {{- include "athens.metaLabels" . | nindent 4 }}
data:
  FilterForUpstreamProxy: |-
    # FilterFile for fetching modules directly from upstream proxy
    D
{{- end -}}
