{{- if .Values.jaeger.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-jaeger
  labels:
    {{- include "athens.metaLabels" (dict "appSuffix" "-jaeger" "Values" .Values "Release" .Release "Chart" .Chart) | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "fullname" . }}-jaeger
      release: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        {{- include "athens.metaLabels" (dict "appSuffix" "-jaeger" "Values" .Values "Release" .Release "Chart" .Chart) | nindent 8 }}
      {{- if .Values.jaeger.annotations }}
      annotations:
        {{- toYaml .Values.jaeger.annotations | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - env:
            - name: COLLECTOR_ZIPKIN_HTTP_PORT
              value: "9441"
          image: "{{ .Values.jaeger.image.repository }}:{{ .Values.jaeger.image.tag }}"
          name: {{ template "fullname" . }}-jaeger
          ports:
            - containerPort: 14268
              protocol: TCP
            - containerPort: 5775
              protocol: UDP
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
            - containerPort: 5778
              protocol: TCP
            - containerPort: 16686
              protocol: TCP
            - containerPort: 9411
              protocol: TCP
{{- end -}}
