kind: Secret
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}-secret
type: Opaque
data:
  {{- if .Values.storage.mongo.url }}
  ATHENS_MONGO_STORAGE_URL: {{ .Values.storage.mongo.url | quote }}
  {{- end }}
  {{- if .Values.storage.s3.accessKey }}
  AWS_ACCESS_KEY_ID: {{ .Values.storage.s3.accessKey | quote }}
  {{- end }}
  {{- if .Values.storage.s3.secretKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.storage.s3.secretKey | quote }}
  {{- end }}
  {{- if .Values.storage.s3.sessionToken }}
  AWS_SESSION_TOKEN: {{ .Values.storage.s3.sessionToken | quote }}
  {{- end }}
  {{- if .Values.storage.gcp.serviceAccount }}
  ATHENS_STORAGE_GCP_JSON_KEY: {{ .Values.storage.gcp.serviceAccount | b64enc | quote }}
  {{- end }}
  {{- if .Values.storage.minio.accessKey }}
  ATHENS_MINIO_ACCESS_KEY_ID: {{ .Values.storage.minio.accessKey | quote }}
  {{- end }}
  {{- if .Values.storage.minio.secretKey }}
  ATHENS_MINIO_SECRET_ACCESS_KEY: {{ .Values.storage.minio.secretKey | quote }}
  {{- end }}
