kind: Secret
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}-secret
  labels:
    {{- include "athens.metaLabels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.storage.mongo.url }}
  ATHENS_MONGO_STORAGE_URL: {{ .Values.storage.mongo.url | b64enc | quote }}
  {{- end }}
  {{- if .Values.storage.s3.accessKey }}
  AWS_ACCESS_KEY_ID: {{ .Values.storage.s3.accessKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.storage.s3.secretKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.storage.s3.secretKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.storage.s3.sessionToken }}
  AWS_SESSION_TOKEN: {{ .Values.storage.s3.sessionToken | b64enc | quote }}
  {{- end }}
  {{- if .Values.storage.gcp.serviceAccount }}
  ATHENS_STORAGE_GCP_JSON_KEY: {{ .Values.storage.gcp.serviceAccount | b64enc | quote }}
  {{- end }}
  {{- if .Values.storage.minio.accessKey }}
  ATHENS_MINIO_ACCESS_KEY_ID: {{ .Values.storage.minio.accessKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.storage.minio.secretKey }}
  ATHENS_MINIO_SECRET_ACCESS_KEY: {{ .Values.storage.minio.secretKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.singleFlight.redis.password }}
  ATHENS_SINGLE_FLIGHT_REDIS_PASSWORD: {{ .Values.singleFlight.redis.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.singleFlight.redisSentinel.sentinelPassword }}
  ATHENS_SINGLE_FLIGHT_REDIS_SENTINEL_SENTINEL_PASSWORD: {{ .Values.singleFlight.redisSentinel.sentinelPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.singleFlight.redisSentinel.redisPassword }}
  ATHENS_SINGLE_FLIGHT_REDIS_SENTINEL_REDIS_PASSWORD: {{ .Values.singleFlight.redisSentinel.redisPassword | b64enc | quote }}
  {{- end }}
