{{- if .Values.sshGitServers -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}-ssh-git-servers
  labels:
    {{- include "athens.metaLabels" . | nindent 4 }}
type: Opaque
data:
{{- range $server := .Values.sshGitServers }}
  {{ if (not $server.existingSecret) }}
  id_rsa-{{ $server.host }}: {{ $server.privateKey | b64enc | quote }}
  {{ end }}
{{- end }}
{{- end -}}
