apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "athens.metaLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.servicePort }}
    targetPort: 3000
    protocol: TCP
    {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort .Values.service.nodePort.port }}
    nodePort: {{ .Values.service.nodePort.port }}
    {{- end }}
  selector:
    app: {{ template "fullname" . }}
    release: "{{ .Release.Name }}"
