ingress:
  enabled: true
  annotations:
  hosts:
    - host: athens-proxy.local
      paths:
        - path: /
          pathType: ImplementationSpecific
extraLabels:
  athensIs: "awesome"
annotations:
  test.annotation: "athens-proxy"
configEnvVars:
  - name: KEY
    value: "value"
image:
  runAsNonRoot: true
securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
jaeger:
  enabled: true
  annotations:
    test.annotation: "jaeger"
service:
  type: "NodePort"
terminationGracePeriodSeconds: 60
lifecycle:
  preStop:
    exec:
      command: [ "/bin/sleep", "10" ]
