ingress:
  enabled: true
  annotations:
  hosts:
    - host: athens-proxy.local
      paths:
        - path: /
          pathType: ImplementationSpecific
jaeger:
  enabled: true
extraLabels:
  athensIs: "awesome"
securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
